[2024-07-17T09:49:59.755+0000] {processor.py:157} INFO - Started process (PID=162) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:49:59.756+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:49:59.757+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:49:59.757+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:50:01.368+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:50:01.450+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:50:01.449+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:50:01.480+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:50:01.479+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:50:01.496+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 1.744 seconds
[2024-07-17T09:50:06.550+0000] {processor.py:157} INFO - Started process (PID=218) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:50:06.552+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:50:06.552+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:50:06.552+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:50:07.237+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:50:07.255+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:50:07.255+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:50:07.274+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:50:07.274+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:50:07.291+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.744 seconds
[2024-07-17T09:50:32.477+0000] {processor.py:157} INFO - Started process (PID=162) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:50:32.478+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:50:32.479+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:50:32.478+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:50:33.751+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:50:33.775+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:50:33.774+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:50:33.795+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:50:33.795+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:50:33.808+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 1.337 seconds
[2024-07-17T09:51:03.981+0000] {processor.py:157} INFO - Started process (PID=192) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:51:03.982+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:51:03.983+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:51:03.983+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:51:04.543+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:51:04.560+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:51:04.560+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:51:04.577+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:51:04.577+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:51:04.590+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.611 seconds
[2024-07-17T09:51:34.848+0000] {processor.py:157} INFO - Started process (PID=221) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:51:34.849+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:51:34.850+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:51:34.850+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:51:35.449+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:51:35.472+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:51:35.472+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:51:35.490+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:51:35.490+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:51:35.507+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.661 seconds
[2024-07-17T09:51:53.365+0000] {processor.py:157} INFO - Started process (PID=250) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:51:53.366+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:51:53.366+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:51:53.366+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:51:53.893+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:51:53.913+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:51:53.913+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:51:53.933+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:51:53.933+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:51:53.954+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.592 seconds
[2024-07-17T09:52:00.656+0000] {processor.py:157} INFO - Started process (PID=279) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:52:00.657+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:52:00.658+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:52:00.658+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:52:01.165+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:52:01.185+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:52:01.184+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:52:01.205+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:52:01.205+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:52:01.221+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.567 seconds
[2024-07-17T09:52:31.284+0000] {processor.py:157} INFO - Started process (PID=308) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:52:31.285+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:52:31.285+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:52:31.285+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:52:31.817+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:52:31.838+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:52:31.838+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:52:31.857+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:52:31.857+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:52:31.873+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.591 seconds
[2024-07-17T09:52:58.624+0000] {processor.py:157} INFO - Started process (PID=337) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:52:58.625+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:52:58.625+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:52:58.625+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:52:59.145+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:52:59.168+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:52:59.167+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:52:59.317+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:52:59.317+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:52:59.337+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.715 seconds
[2024-07-17T09:53:29.494+0000] {processor.py:157} INFO - Started process (PID=366) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:53:29.495+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:53:29.495+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:53:29.495+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:53:30.017+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:53:30.041+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:53:30.041+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:53:30.206+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:53:30.206+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:53:30.222+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.731 seconds
[2024-07-17T09:54:00.458+0000] {processor.py:157} INFO - Started process (PID=395) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:54:00.459+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:54:00.459+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:54:00.459+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:54:00.987+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:54:01.008+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:54:01.008+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:54:01.135+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:54:01.134+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:54:01.152+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.697 seconds
[2024-07-17T09:54:31.343+0000] {processor.py:157} INFO - Started process (PID=424) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:54:31.344+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:54:31.344+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:54:31.344+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:54:31.864+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:54:31.886+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:54:31.885+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:54:31.905+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:54:31.905+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:54:31.921+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.581 seconds
[2024-07-17T09:55:02.046+0000] {processor.py:157} INFO - Started process (PID=453) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:55:02.047+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:55:02.048+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:55:02.048+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:55:02.527+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:55:02.548+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:55:02.548+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:55:02.566+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:55:02.566+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:55:02.583+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.539 seconds
[2024-07-17T09:55:32.788+0000] {processor.py:157} INFO - Started process (PID=508) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:55:32.789+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:55:32.789+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:55:32.789+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:55:33.314+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:55:33.336+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:55:33.335+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:55:33.355+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:55:33.355+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:55:33.372+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.587 seconds
[2024-07-17T09:56:03.505+0000] {processor.py:157} INFO - Started process (PID=537) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:56:03.505+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:56:03.506+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:56:03.506+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:56:04.051+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:56:04.072+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:56:04.072+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:56:04.210+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:56:04.210+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:56:04.226+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.724 seconds
[2024-07-17T09:56:34.438+0000] {processor.py:157} INFO - Started process (PID=566) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:56:34.439+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:56:34.440+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:56:34.440+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:56:34.944+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:56:34.968+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:56:34.967+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:56:35.098+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:56:35.098+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:56:35.114+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.678 seconds
[2024-07-17T09:57:05.337+0000] {processor.py:157} INFO - Started process (PID=595) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:57:05.338+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:57:05.339+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:57:05.339+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:57:05.890+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:57:05.916+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:57:05.915+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:57:05.939+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:57:05.939+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:57:05.958+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.624 seconds
[2024-07-17T09:57:36.168+0000] {processor.py:157} INFO - Started process (PID=624) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:57:36.168+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:57:36.169+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:57:36.169+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:57:36.671+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:57:36.693+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:57:36.692+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:57:36.712+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:57:36.712+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:57:36.727+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.561 seconds
[2024-07-17T09:59:00.229+0000] {processor.py:157} INFO - Started process (PID=162) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:59:00.230+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:59:00.231+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:59:00.231+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:59:01.689+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:59:01.717+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:59:01.716+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:59:01.735+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:59:01.735+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:59:01.753+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 1.526 seconds
[2024-07-17T09:59:31.997+0000] {processor.py:157} INFO - Started process (PID=192) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T09:59:31.999+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T09:59:31.999+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:59:31.999+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:59:32.573+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T09:59:32.591+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:59:32.590+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T09:59:32.608+0000] {logging_mixin.py:149} INFO - [2024-07-17T09:59:32.608+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T09:59:32.628+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.633 seconds
[2024-07-17T10:00:02.847+0000] {processor.py:157} INFO - Started process (PID=271) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:00:02.848+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:00:02.848+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:00:02.848+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:00:03.483+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:00:03.502+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:00:03.501+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:00:03.518+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:00:03.518+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:00:03.533+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.694 seconds
[2024-07-17T10:00:33.888+0000] {processor.py:157} INFO - Started process (PID=300) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:00:33.889+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:00:33.889+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:00:33.889+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:00:34.368+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:00:34.388+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:00:34.387+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:00:34.406+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:00:34.406+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:00:34.423+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.538 seconds
[2024-07-17T10:01:04.642+0000] {processor.py:157} INFO - Started process (PID=329) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:01:04.643+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:01:04.643+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:01:04.643+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:01:05.140+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:01:05.160+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:01:05.160+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:01:05.180+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:01:05.180+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:01:05.197+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.557 seconds
[2024-07-17T10:01:35.449+0000] {processor.py:157} INFO - Started process (PID=358) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:01:35.450+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:01:35.451+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:01:35.451+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:01:35.965+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:01:35.984+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:01:35.984+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:01:36.099+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:01:36.099+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:01:36.115+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.668 seconds
[2024-07-17T10:02:06.339+0000] {processor.py:157} INFO - Started process (PID=387) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:02:06.340+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:02:06.341+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:02:06.340+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:02:06.890+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:02:06.914+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:02:06.914+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:02:07.056+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:02:07.056+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:02:07.075+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.740 seconds
[2024-07-17T10:02:37.275+0000] {processor.py:157} INFO - Started process (PID=416) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:02:37.277+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:02:37.278+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:02:37.277+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:02:37.862+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:02:37.889+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:02:37.889+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:02:38.038+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:02:38.037+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:02:38.055+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.782 seconds
[2024-07-17T10:03:08.261+0000] {processor.py:157} INFO - Started process (PID=445) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:03:08.262+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:03:08.263+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:03:08.263+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:03:08.848+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:03:08.872+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:03:08.872+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:03:08.893+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:03:08.893+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:03:08.910+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.652 seconds
[2024-07-17T10:03:39.093+0000] {processor.py:157} INFO - Started process (PID=474) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:03:39.094+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:03:39.095+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:03:39.095+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:03:39.591+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:03:39.611+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:03:39.611+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:03:39.632+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:03:39.632+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:03:39.650+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.559 seconds
[2024-07-17T10:04:09.772+0000] {processor.py:157} INFO - Started process (PID=503) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:04:09.773+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:04:09.774+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:04:09.774+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:04:10.383+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:04:10.408+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:04:10.408+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:04:10.429+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:04:10.428+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:04:10.447+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.678 seconds
[2024-07-17T10:04:40.667+0000] {processor.py:157} INFO - Started process (PID=532) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:04:40.668+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:04:40.669+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:04:40.669+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:04:41.181+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:04:41.203+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:04:41.202+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:04:41.333+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:04:41.332+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:04:41.350+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.686 seconds
[2024-07-17T10:05:11.599+0000] {processor.py:157} INFO - Started process (PID=561) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:05:11.600+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:05:11.601+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:05:11.600+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:05:12.106+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:05:12.128+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:05:12.128+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:05:12.255+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:05:12.255+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:05:12.270+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.674 seconds
[2024-07-17T10:05:42.450+0000] {processor.py:157} INFO - Started process (PID=590) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:05:42.451+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:05:42.452+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:05:42.452+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:05:42.964+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:05:42.986+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:05:42.984+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:05:43.005+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:05:43.005+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:05:43.021+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.574 seconds
[2024-07-17T10:06:13.207+0000] {processor.py:157} INFO - Started process (PID=619) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:06:13.208+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:06:13.209+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:06:13.209+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:06:13.714+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:06:13.734+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:06:13.734+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:06:13.757+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:06:13.756+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:06:13.775+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.571 seconds
[2024-07-17T10:06:43.849+0000] {processor.py:157} INFO - Started process (PID=648) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:06:43.850+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:06:43.851+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:06:43.851+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:06:44.351+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:06:44.371+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:06:44.371+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:06:44.389+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:06:44.389+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:06:44.406+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.560 seconds
[2024-07-17T10:07:14.696+0000] {processor.py:157} INFO - Started process (PID=677) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:07:14.697+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:07:14.698+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:07:14.698+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:07:15.207+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:07:15.228+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:07:15.228+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:07:15.245+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:07:15.245+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:07:15.263+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.569 seconds
[2024-07-17T10:07:45.495+0000] {processor.py:157} INFO - Started process (PID=706) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:07:45.496+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:07:45.497+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:07:45.497+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:07:46.047+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:07:46.067+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:07:46.067+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:07:46.192+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:07:46.192+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:07:46.209+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.717 seconds
[2024-07-17T10:08:11.466+0000] {processor.py:157} INFO - Started process (PID=735) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:08:11.467+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:08:11.468+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:08:11.468+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:08:12.005+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:08:12.025+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:08:12.025+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:08:12.155+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:08:12.155+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:08:12.180+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.716 seconds
[2024-07-17T10:08:32.343+0000] {processor.py:157} INFO - Started process (PID=764) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:08:32.344+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:08:32.345+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:08:32.345+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:08:36.563+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:08:36.554+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/run_notebook.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5e00548410>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='jupyter-server', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5e00548410>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_notebook.py", line 20, in <module>
    token = get_jupyter_token("http://jupyter-server:8888", "your_jupyter_password")
  File "/opt/airflow/dags/run_notebook.py", line 13, in get_jupyter_token
    response = requests.post(f"{jupyter_url}/login", json={"password": password})
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='jupyter-server', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5e00548410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2024-07-17T10:08:36.564+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:08:36.577+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 4.237 seconds
[2024-07-17T10:08:50.510+0000] {processor.py:157} INFO - Started process (PID=793) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:08:50.511+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:08:50.512+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:08:50.512+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:08:54.719+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:08:54.715+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/run_notebook.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5e00542e90>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='jupyter-server', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5e00542e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_notebook.py", line 20, in <module>
    token = get_jupyter_token("http://jupyter-server:8888", "omkar")
  File "/opt/airflow/dags/run_notebook.py", line 13, in get_jupyter_token
    response = requests.post(f"{jupyter_url}/login", json={"password": password})
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='jupyter-server', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5e00542e90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2024-07-17T10:08:54.720+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:08:54.733+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 4.225 seconds
[2024-07-17T10:09:03.803+0000] {processor.py:157} INFO - Started process (PID=822) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:09:03.804+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:09:03.804+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:09:03.804+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:09:04.292+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:09:04.290+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/run_notebook.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_notebook.py", line 20, in <module>
    token = get_jupyter_token("http://:8888", "omkar")
  File "/opt/airflow/dags/run_notebook.py", line 13, in get_jupyter_token
    response = requests.post(f"{jupyter_url}/login", json={"password": password})
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 445, in prepare_url
    raise InvalidURL(f"Invalid URL {url!r}: No host supplied")
requests.exceptions.InvalidURL: Invalid URL 'http://:8888/login': No host supplied
[2024-07-17T10:09:04.293+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:09:04.310+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.509 seconds
[2024-07-17T10:09:14.427+0000] {processor.py:157} INFO - Started process (PID=851) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:09:14.428+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:09:14.428+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:09:14.428+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:09:14.966+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:09:14.962+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/run_notebook.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5e00541dd0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5e00541dd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_notebook.py", line 20, in <module>
    token = get_jupyter_token("http://host.docker.internal:8888", "omkar")
  File "/opt/airflow/dags/run_notebook.py", line 13, in get_jupyter_token
    response = requests.post(f"{jupyter_url}/login", json={"password": password})
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='host.docker.internal', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5e00541dd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-07-17T10:09:14.967+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:09:14.981+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.557 seconds
[2024-07-17T10:09:15.914+0000] {processor.py:157} INFO - Started process (PID=880) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:09:15.915+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:09:15.916+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:09:15.916+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:09:16.398+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:09:16.394+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/run_notebook.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5e00541c10>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5e00541c10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_notebook.py", line 20, in <module>
    token = get_jupyter_token("http://host.docker.internal:8888", "omkar")
  File "/opt/airflow/dags/run_notebook.py", line 13, in get_jupyter_token
    response = requests.post(f"{jupyter_url}/login", json={"password": password})
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='host.docker.internal', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5e00541c10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-07-17T10:09:16.399+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:09:16.415+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.503 seconds
[2024-07-17T10:09:20.475+0000] {processor.py:157} INFO - Started process (PID=909) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:09:20.476+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:09:20.476+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:09:20.476+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:09:21.025+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:09:21.021+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/run_notebook.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5e0053dd50>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5e0053dd50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_notebook.py", line 20, in <module>
    token = get_jupyter_token("http://host.docker.internal:8888", "omkar")
  File "/opt/airflow/dags/run_notebook.py", line 13, in get_jupyter_token
    response = requests.post(f"{jupyter_url}/login", json={"password": password})
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='host.docker.internal', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5e0053dd50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-07-17T10:09:21.026+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:09:21.042+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.570 seconds
[2024-07-17T10:09:29.095+0000] {processor.py:157} INFO - Started process (PID=938) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:09:29.096+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:09:29.097+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:09:29.097+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:09:29.589+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:09:29.584+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/run_notebook.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5e00542510>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5e00542510>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_notebook.py", line 20, in <module>
    token = get_jupyter_token("http://host.docker.internal:8888", "omkar")
  File "/opt/airflow/dags/run_notebook.py", line 13, in get_jupyter_token
    response = requests.post(f"{jupyter_url}/login", json={"password": password})
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='host.docker.internal', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5e00542510>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-07-17T10:09:29.590+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:09:29.603+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.510 seconds
[2024-07-17T10:09:37.689+0000] {processor.py:157} INFO - Started process (PID=967) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:09:37.690+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:09:37.691+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:09:37.691+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:09:38.225+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:09:38.221+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/run_notebook.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5e00542b90>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5e00542b90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_notebook.py", line 20, in <module>
    token = get_jupyter_token("http://host.docker.internal:8888", "omkar")
  File "/opt/airflow/dags/run_notebook.py", line 13, in get_jupyter_token
    response = requests.post(f"{jupyter_url}/login", json={"password": password})
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='host.docker.internal', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5e00542b90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2024-07-17T10:09:38.226+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:09:38.241+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.554 seconds
[2024-07-17T10:11:28.775+0000] {processor.py:157} INFO - Started process (PID=162) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:11:28.777+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:11:28.778+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:11:28.777+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:11:30.441+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:11:30.438+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/run_notebook.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_notebook.py", line 20, in <module>
    token = get_jupyter_token("http://host.docker.internal:8888", "omkar")
  File "/opt/airflow/dags/run_notebook.py", line 17, in get_jupyter_token
    raise Exception("Failed to retrieve Jupyter token")
Exception: Failed to retrieve Jupyter token
[2024-07-17T10:11:30.442+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:11:30.455+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 1.682 seconds
[2024-07-17T10:12:00.634+0000] {processor.py:157} INFO - Started process (PID=192) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:12:00.635+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:12:00.636+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:12:00.636+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:12:01.296+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:12:01.294+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/run_notebook.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_notebook.py", line 20, in <module>
    token = get_jupyter_token("http://host.docker.internal:8888", "omkar")
  File "/opt/airflow/dags/run_notebook.py", line 17, in get_jupyter_token
    raise Exception("Failed to retrieve Jupyter token")
Exception: Failed to retrieve Jupyter token
[2024-07-17T10:12:01.297+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:12:01.310+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.680 seconds
[2024-07-17T10:12:31.633+0000] {processor.py:157} INFO - Started process (PID=221) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:12:31.634+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:12:31.634+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:12:31.634+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:12:32.129+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:12:32.127+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/run_notebook.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_notebook.py", line 20, in <module>
    token = get_jupyter_token("http://host.docker.internal:8888", "omkar")
  File "/opt/airflow/dags/run_notebook.py", line 17, in get_jupyter_token
    raise Exception("Failed to retrieve Jupyter token")
Exception: Failed to retrieve Jupyter token
[2024-07-17T10:12:32.130+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:12:32.146+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.516 seconds
[2024-07-17T10:13:02.331+0000] {processor.py:157} INFO - Started process (PID=250) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:13:02.332+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:13:02.333+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:13:02.333+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:13:02.904+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:13:02.901+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/run_notebook.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_notebook.py", line 20, in <module>
    token = get_jupyter_token("http://host.docker.internal:8888", "omkar")
  File "/opt/airflow/dags/run_notebook.py", line 17, in get_jupyter_token
    raise Exception("Failed to retrieve Jupyter token")
Exception: Failed to retrieve Jupyter token
[2024-07-17T10:13:02.905+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:13:02.920+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.591 seconds
[2024-07-17T10:13:33.000+0000] {processor.py:157} INFO - Started process (PID=279) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:13:33.001+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:13:33.001+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:13:33.001+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:13:33.517+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:13:33.513+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/run_notebook.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_notebook.py", line 20, in <module>
    token = get_jupyter_token("http://host.docker.internal:8888", "omkar")
  File "/opt/airflow/dags/run_notebook.py", line 17, in get_jupyter_token
    raise Exception("Failed to retrieve Jupyter token")
Exception: Failed to retrieve Jupyter token
[2024-07-17T10:13:33.517+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:13:33.533+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.539 seconds
[2024-07-17T10:14:03.738+0000] {processor.py:157} INFO - Started process (PID=308) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:03.739+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:14:03.740+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:14:03.740+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:04.250+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:14:04.247+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/run_notebook.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_notebook.py", line 20, in <module>
    token = get_jupyter_token("http://host.docker.internal:8888", "omkar")
  File "/opt/airflow/dags/run_notebook.py", line 17, in get_jupyter_token
    raise Exception("Failed to retrieve Jupyter token")
Exception: Failed to retrieve Jupyter token
[2024-07-17T10:14:04.251+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:04.267+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.531 seconds
[2024-07-17T10:14:15.384+0000] {processor.py:157} INFO - Started process (PID=337) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:15.384+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:14:15.385+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:14:15.385+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:15.406+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:15.461+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:14:15.461+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:14:15.477+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:14:15.476+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:14:15.500+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.118 seconds
[2024-07-17T10:14:16.409+0000] {processor.py:157} INFO - Started process (PID=342) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:16.409+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:14:16.410+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:14:16.410+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:16.427+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:16.437+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:14:16.437+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:14:16.455+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:14:16.455+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:14:16.478+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.072 seconds
[2024-07-17T10:14:35.590+0000] {processor.py:157} INFO - Started process (PID=347) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:35.590+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:14:35.591+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:14:35.591+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:35.607+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:14:35.604+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/run_notebook.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_notebook.py", line 5, in <module>
    impo
NameError: name 'impo' is not defined
[2024-07-17T10:14:35.607+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:35.625+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.038 seconds
[2024-07-17T10:14:38.663+0000] {processor.py:157} INFO - Started process (PID=352) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:38.663+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:14:38.664+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:14:38.664+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:38.682+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:38.692+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:14:38.692+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:14:38.711+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:14:38.711+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:14:38.732+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.072 seconds
[2024-07-17T10:14:42.699+0000] {processor.py:157} INFO - Started process (PID=357) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:42.699+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:14:42.700+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:14:42.700+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:42.718+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:42.728+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:14:42.727+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:14:42.746+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:14:42.746+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:14:42.766+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.069 seconds
[2024-07-17T10:14:43.785+0000] {processor.py:157} INFO - Started process (PID=362) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:43.786+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:14:43.787+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:14:43.787+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:43.806+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:14:43.816+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:14:43.816+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:14:43.836+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:14:43.836+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:14:43.854+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.071 seconds
[2024-07-17T10:15:12.755+0000] {processor.py:157} INFO - Started process (PID=162) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:15:12.756+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:15:12.757+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:15:12.757+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:15:12.777+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:15:12.809+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:15:12.808+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:15:12.908+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:15:12.907+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:15:12.922+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.169 seconds
[2024-07-17T10:15:42.952+0000] {processor.py:157} INFO - Started process (PID=168) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:15:42.953+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:15:42.954+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:15:42.954+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:15:42.966+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:15:43.071+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:15:43.071+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:15:43.087+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:15:43.087+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:15:43.104+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.154 seconds
[2024-07-17T10:16:13.282+0000] {processor.py:157} INFO - Started process (PID=175) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:16:13.282+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:16:13.283+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:16:13.283+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:16:13.382+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:16:13.401+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:16:13.401+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:16:13.417+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:16:13.417+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:16:13.434+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.155 seconds
[2024-07-17T10:16:43.695+0000] {processor.py:157} INFO - Started process (PID=180) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:16:43.696+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:16:43.697+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:16:43.696+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:16:43.709+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:16:43.732+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:16:43.732+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:16:43.750+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:16:43.750+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:16:43.767+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.074 seconds
[2024-07-17T10:17:13.971+0000] {processor.py:157} INFO - Started process (PID=185) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:17:13.972+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:17:13.975+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:17:13.974+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:17:13.999+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:17:14.023+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:17:14.023+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:17:14.045+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:17:14.045+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:17:14.063+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.098 seconds
[2024-07-17T10:17:44.144+0000] {processor.py:157} INFO - Started process (PID=190) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:17:44.145+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:17:44.146+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:17:44.146+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:17:44.159+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:17:44.180+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:17:44.180+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:17:44.200+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:17:44.199+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:17:44.217+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.075 seconds
[2024-07-17T10:17:57.344+0000] {processor.py:157} INFO - Started process (PID=195) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:17:57.344+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:17:57.345+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:17:57.345+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:18:02.178+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:18:02.172+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/run_notebook.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f04d2b2c710>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='jupyter-server', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f04d2b2c710>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_notebook.py", line 20, in <module>
    token = get_jupyter_token("http://:8888", "omkar")
  File "/opt/airflow/dags/run_notebook.py", line 13, in get_jupyter_token
    response = requests.post(f"{jupyter_url}/login", json={"password": password})
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='jupyter-server', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f04d2b2c710>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2024-07-17T10:18:02.179+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:18:02.192+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 4.851 seconds
[2024-07-17T10:18:03.228+0000] {processor.py:157} INFO - Started process (PID=224) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:18:03.229+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:18:03.229+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:18:03.229+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:18:07.500+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:18:07.484+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/run_notebook.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f047eb9d5d0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='jupyter-server', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f047eb9d5d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_notebook.py", line 20, in <module>
    notebook_content = response.json()
  File "/opt/airflow/dags/run_notebook.py", line 13, in get_jupyter_token
    token = "enter_jupyter_token"
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='jupyter-server', port=8888): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f047eb9d5d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2024-07-17T10:18:07.501+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:18:07.514+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 4.288 seconds
[2024-07-17T10:18:08.422+0000] {processor.py:157} INFO - Started process (PID=253) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:18:08.423+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:18:08.424+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:18:08.423+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:18:08.922+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:18:09.065+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:18:09.064+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:18:09.080+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:18:09.080+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:18:09.099+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.679 seconds
[2024-07-17T10:18:39.374+0000] {processor.py:157} INFO - Started process (PID=282) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:18:39.375+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:18:39.376+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:18:39.375+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:18:39.896+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:18:39.915+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:18:39.914+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:18:39.932+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:18:39.932+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:18:39.948+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.577 seconds
[2024-07-17T10:19:10.119+0000] {processor.py:157} INFO - Started process (PID=311) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:19:10.120+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:19:10.121+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:19:10.120+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:19:10.655+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:19:10.674+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:19:10.674+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:19:10.692+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:19:10.692+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:19:10.706+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.589 seconds
[2024-07-17T10:19:40.964+0000] {processor.py:157} INFO - Started process (PID=340) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:19:40.964+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:19:40.965+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:19:40.965+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:19:41.445+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:19:41.467+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:19:41.467+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:19:41.489+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:19:41.489+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:19:41.505+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.544 seconds
[2024-07-17T10:45:34.142+0000] {processor.py:157} INFO - Started process (PID=162) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:45:34.143+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:45:34.143+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:45:34.143+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:45:34.165+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:45:34.352+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:45:34.351+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:45:34.370+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:45:34.370+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:45:34.387+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.247 seconds
[2024-07-17T10:46:04.630+0000] {processor.py:157} INFO - Started process (PID=170) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:46:04.631+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:46:04.632+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:46:04.632+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:46:04.648+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:46:04.755+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:46:04.754+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:46:04.770+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:46:04.770+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:46:04.786+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.159 seconds
[2024-07-17T10:46:34.813+0000] {processor.py:157} INFO - Started process (PID=177) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:46:34.814+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:46:34.815+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:46:34.815+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:46:34.923+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:46:34.946+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:46:34.945+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:46:34.965+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:46:34.965+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:46:34.980+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.169 seconds
[2024-07-17T10:47:05.189+0000] {processor.py:157} INFO - Started process (PID=182) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:47:05.190+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:47:05.191+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:47:05.191+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:47:05.215+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:47:05.247+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:47:05.247+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:47:05.267+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:47:05.267+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:47:05.296+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.109 seconds
[2024-07-17T10:47:35.479+0000] {processor.py:157} INFO - Started process (PID=187) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:47:35.480+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:47:35.480+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:47:35.480+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:47:35.492+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:47:35.511+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:47:35.511+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:47:35.528+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:47:35.528+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:47:35.554+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.077 seconds
[2024-07-17T10:48:05.669+0000] {processor.py:157} INFO - Started process (PID=192) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:48:05.670+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:48:05.671+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:48:05.671+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:48:05.685+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:48:05.708+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:48:05.708+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:48:05.730+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:48:05.730+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:48:05.747+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.081 seconds
[2024-07-17T10:48:31.490+0000] {processor.py:157} INFO - Started process (PID=162) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:48:31.491+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:48:31.492+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:48:31.492+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:48:31.508+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:48:31.544+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:48:31.544+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:48:31.655+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:48:31.655+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:48:31.671+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.183 seconds
[2024-07-17T10:49:01.742+0000] {processor.py:157} INFO - Started process (PID=168) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:49:01.743+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:49:01.744+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:49:01.743+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:49:01.755+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:49:01.859+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:49:01.859+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:49:01.875+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:49:01.875+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:49:01.890+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.150 seconds
[2024-07-17T10:49:31.982+0000] {processor.py:157} INFO - Started process (PID=173) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:49:31.982+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:49:31.983+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:49:31.983+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:49:32.092+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:49:32.111+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:49:32.111+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:49:32.128+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:49:32.127+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:49:32.145+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.166 seconds
[2024-07-17T10:50:02.365+0000] {processor.py:157} INFO - Started process (PID=178) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:50:02.365+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:50:02.366+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:50:02.366+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:50:02.378+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:50:02.398+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:50:02.398+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:50:02.416+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:50:02.416+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:50:02.432+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.070 seconds
[2024-07-17T10:50:32.592+0000] {processor.py:157} INFO - Started process (PID=185) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:50:32.592+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:50:32.593+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:50:32.593+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:50:32.607+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:50:32.629+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:50:32.629+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:50:32.648+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:50:32.648+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:50:32.664+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.075 seconds
[2024-07-17T10:51:02.840+0000] {processor.py:157} INFO - Started process (PID=190) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:51:02.841+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:51:02.841+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:51:02.841+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:51:02.857+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:51:02.883+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:51:02.883+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:51:02.905+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:51:02.905+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:51:02.921+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.084 seconds
[2024-07-17T10:51:33.062+0000] {processor.py:157} INFO - Started process (PID=197) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:51:33.063+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:51:33.064+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:51:33.064+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:51:33.077+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:51:33.099+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:51:33.099+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:51:33.117+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:51:33.117+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:51:33.132+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.071 seconds
[2024-07-17T10:52:03.296+0000] {processor.py:157} INFO - Started process (PID=202) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:52:03.296+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:52:03.297+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:52:03.297+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:52:03.310+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:52:03.331+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:52:03.331+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:52:03.349+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:52:03.349+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:52:03.364+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.071 seconds
[2024-07-17T10:52:26.507+0000] {processor.py:157} INFO - Started process (PID=207) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:52:26.508+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:52:26.509+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:52:26.509+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:52:27.619+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:52:27.667+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:52:27.666+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:52:27.683+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:52:27.683+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:52:27.819+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 1.316 seconds
[2024-07-17T10:52:29.565+0000] {processor.py:157} INFO - Started process (PID=236) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:52:29.566+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:52:29.566+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:52:29.566+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:52:30.052+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:52:30.063+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:52:30.063+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:52:30.082+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:52:30.082+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:52:30.100+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.537 seconds
[2024-07-17T10:52:55.432+0000] {processor.py:157} INFO - Started process (PID=162) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:52:55.432+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:52:55.433+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:52:55.433+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:52:56.532+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:52:56.542+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:52:56.542+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:52:56.559+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:52:56.559+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:52:56.577+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 1.147 seconds
[2024-07-17T10:53:09.552+0000] {processor.py:157} INFO - Started process (PID=192) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:53:09.552+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:53:09.553+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:53:09.553+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:53:10.175+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:53:10.197+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:53:10.197+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:53:10.216+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:53:10.216+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:53:10.232+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.682 seconds
[2024-07-17T10:53:45.109+0000] {processor.py:157} INFO - Started process (PID=162) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:53:45.111+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:53:45.112+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:53:45.112+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:53:46.326+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:53:46.349+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:53:46.348+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:53:46.368+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:53:46.367+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:53:46.383+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 1.277 seconds
[2024-07-17T10:54:16.574+0000] {processor.py:157} INFO - Started process (PID=242) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:54:16.574+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:54:16.575+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:54:16.575+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:54:17.168+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T10:54:17.185+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:54:17.184+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T10:54:17.202+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:54:17.202+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T10:54:17.218+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.647 seconds
[2024-07-17T10:54:47.459+0000] {processor.py:157} INFO - Started process (PID=335) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T10:54:47.460+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T10:54:47.461+0000] {logging_mixin.py:149} INFO - [2024-07-17T10:54:47.461+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T12:27:30.881+0000] {processor.py:157} INFO - Started process (PID=162) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T12:27:30.884+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T12:27:30.887+0000] {logging_mixin.py:149} INFO - [2024-07-17T12:27:30.886+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T12:27:33.470+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T12:27:33.512+0000] {logging_mixin.py:149} INFO - [2024-07-17T12:27:33.512+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T12:27:33.539+0000] {logging_mixin.py:149} INFO - [2024-07-17T12:27:33.539+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T12:27:33.570+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 2.708 seconds
[2024-07-17T12:28:03.910+0000] {processor.py:157} INFO - Started process (PID=242) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T12:28:03.912+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T12:28:03.913+0000] {logging_mixin.py:149} INFO - [2024-07-17T12:28:03.913+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T12:28:05.007+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T12:28:05.042+0000] {logging_mixin.py:149} INFO - [2024-07-17T12:28:05.042+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T12:28:05.085+0000] {logging_mixin.py:149} INFO - [2024-07-17T12:28:05.085+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T12:28:05.113+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 1.209 seconds
[2024-07-17T12:28:35.214+0000] {processor.py:157} INFO - Started process (PID=321) to work on /opt/airflow/dags/run_notebook.py
[2024-07-17T12:28:35.216+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/run_notebook.py for tasks to queue
[2024-07-17T12:28:35.218+0000] {logging_mixin.py:149} INFO - [2024-07-17T12:28:35.218+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/run_notebook.py
[2024-07-17T12:28:36.119+0000] {processor.py:836} INFO - DAG(s) dict_keys(['run_remote_jupyter_notebook']) retrieved from /opt/airflow/dags/run_notebook.py
[2024-07-17T12:28:36.145+0000] {logging_mixin.py:149} INFO - [2024-07-17T12:28:36.144+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2024-07-17T12:28:36.170+0000] {logging_mixin.py:149} INFO - [2024-07-17T12:28:36.170+0000] {dag.py:3490} INFO - Setting next_dagrun for run_remote_jupyter_notebook to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-07-17T12:28:36.195+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/run_notebook.py took 0.989 seconds
