[2024-07-15T09:45:40.346+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_jupyter_notebook.run_notebook scheduled__2023-07-09T00:00:00+00:00 [queued]>
[2024-07-15T09:45:40.366+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_jupyter_notebook.run_notebook scheduled__2023-07-09T00:00:00+00:00 [queued]>
[2024-07-15T09:45:40.367+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-15T09:45:40.398+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_notebook> on 2023-07-09 00:00:00+00:00
[2024-07-15T09:45:40.412+0000] {standard_task_runner.py:57} INFO - Started process 4089 to run task
[2024-07-15T09:45:40.423+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_jupyter_notebook', 'run_notebook', 'scheduled__2023-07-09T00:00:00+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/run_notebook.py', '--cfg-path', '/tmp/tmptad98w04']
[2024-07-15T09:45:40.427+0000] {standard_task_runner.py:85} INFO - Job 241: Subtask run_notebook
[2024-07-15T09:45:40.537+0000] {task_command.py:410} INFO - Running <TaskInstance: run_jupyter_notebook.run_notebook scheduled__2023-07-09T00:00:00+00:00 [running]> on host bd21a2046053
[2024-07-15T09:45:40.752+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_jupyter_notebook' AIRFLOW_CTX_TASK_ID='run_notebook' AIRFLOW_CTX_EXECUTION_DATE='2023-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-09T00:00:00+00:00'
[2024-07-15T09:45:44.859+0000] {client.py:566} ERROR - Error occurred while starting new kernel client for kernel 388a9c44-00c5-4e06-a97f-8d237f4c0c45: Kernel died before replying to kernel_info
[2024-07-15T09:45:44.861+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/run_notebook.py", line 16, in execute_notebook
    ep.preprocess(nb, {'metadata': {'path': os.path.dirname(notebook_path)}})
  File "/home/airflow/.local/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 94, in preprocess
    with self.setup_kernel():
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.7/site-packages/nbclient/client.py", line 599, in setup_kernel
    self.start_new_kernel_client()
  File "/home/airflow/.local/lib/python3.7/site-packages/jupyter_core/utils/__init__.py", line 98, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/nbclient/client.py", line 562, in async_start_new_kernel_client
    await ensure_async(self.kc.wait_for_ready(timeout=self.startup_timeout))
  File "/home/airflow/.local/lib/python3.7/site-packages/jupyter_core/utils/__init__.py", line 110, in ensure_async
    result = await obj
  File "/home/airflow/.local/lib/python3.7/site-packages/jupyter_client/client.py", line 202, in _async_wait_for_ready
    raise RuntimeError("Kernel died before replying to kernel_info")
RuntimeError: Kernel died before replying to kernel_info
[2024-07-15T09:45:44.877+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=run_jupyter_notebook, task_id=run_notebook, execution_date=20230709T000000, start_date=20240715T094540, end_date=20240715T094544
[2024-07-15T09:45:44.899+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 241 for task run_notebook (Kernel died before replying to kernel_info; 4089)
[2024-07-15T09:45:44.940+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-07-15T09:45:44.962+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
