[2024-07-15T10:44:06.153+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2023-05-01T00:00:00+00:00 [queued]>
[2024-07-15T10:44:06.183+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2023-05-01T00:00:00+00:00 [queued]>
[2024-07-15T10:44:06.184+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-15T10:44:06.349+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_notebook> on 2023-05-01 00:00:00+00:00
[2024-07-15T10:44:06.359+0000] {standard_task_runner.py:57} INFO - Started process 1197 to run task
[2024-07-15T10:44:06.365+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_remote_jupyter_notebook', 'run_notebook', 'scheduled__2023-05-01T00:00:00+00:00', '--job-id', '709', '--raw', '--subdir', 'DAGS_FOLDER/run_notebook.py', '--cfg-path', '/tmp/tmpj1z48w_j']
[2024-07-15T10:44:06.374+0000] {standard_task_runner.py:85} INFO - Job 709: Subtask run_notebook
[2024-07-15T10:44:06.453+0000] {task_command.py:410} INFO - Running <TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2023-05-01T00:00:00+00:00 [running]> on host 3ef4790ee2bb
[2024-07-15T10:44:06.782+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_remote_jupyter_notebook' AIRFLOW_CTX_TASK_ID='run_notebook' AIRFLOW_CTX_EXECUTION_DATE='2023-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-01T00:00:00+00:00'
[2024-07-15T10:44:06.803+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/run_notebook.py", line 20, in execute_remote_notebook
    notebook_content = response.json()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-15T10:44:06.816+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=run_remote_jupyter_notebook, task_id=run_notebook, execution_date=20230501T000000, start_date=20240715T104406, end_date=20240715T104406
[2024-07-15T10:44:06.835+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 709 for task run_notebook (Expecting value: line 1 column 1 (char 0); 1197)
[2024-07-15T10:44:06.897+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-07-15T10:44:06.921+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-18T06:55:19.001+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2023-05-01T00:00:00+00:00 [queued]>
[2024-07-18T06:55:19.015+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2023-05-01T00:00:00+00:00 [queued]>
[2024-07-18T06:55:19.016+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-18T06:55:19.062+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_notebook> on 2023-05-01 00:00:00+00:00
[2024-07-18T06:55:19.080+0000] {standard_task_runner.py:57} INFO - Started process 6443 to run task
[2024-07-18T06:55:19.095+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_remote_jupyter_notebook', 'run_notebook', 'scheduled__2023-05-01T00:00:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/run_notebook.py', '--cfg-path', '/tmp/tmp_8nwnr6o']
[2024-07-18T06:55:19.109+0000] {standard_task_runner.py:85} INFO - Job 122: Subtask run_notebook
[2024-07-18T06:55:19.220+0000] {task_command.py:410} INFO - Running <TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2023-05-01T00:00:00+00:00 [running]> on host 6c8b3b9a6388
[2024-07-18T06:55:19.442+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_remote_jupyter_notebook' AIRFLOW_CTX_TASK_ID='run_notebook' AIRFLOW_CTX_EXECUTION_DATE='2023-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-01T00:00:00+00:00'
[2024-07-18T06:55:23.215+0000] {logging_mixin.py:149} INFO - Notebook executed and updated successfully on the server.
[2024-07-18T06:55:23.217+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-07-18T06:55:23.241+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=run_remote_jupyter_notebook, task_id=run_notebook, execution_date=20230501T000000, start_date=20240718T065519, end_date=20240718T065523
[2024-07-18T06:55:23.323+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-07-18T06:55:23.359+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
