[2024-07-15T09:48:03.499+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_jupyter_notebook.run_notebook scheduled__2023-12-19T00:00:00+00:00 [queued]>
[2024-07-15T09:48:03.521+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_jupyter_notebook.run_notebook scheduled__2023-12-19T00:00:00+00:00 [queued]>
[2024-07-15T09:48:03.522+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-15T09:48:03.548+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_notebook> on 2023-12-19 00:00:00+00:00
[2024-07-15T09:48:03.556+0000] {standard_task_runner.py:57} INFO - Started process 8351 to run task
[2024-07-15T09:48:03.566+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_jupyter_notebook', 'run_notebook', 'scheduled__2023-12-19T00:00:00+00:00', '--job-id', '404', '--raw', '--subdir', 'DAGS_FOLDER/run_notebook.py', '--cfg-path', '/tmp/tmplh2gugrj']
[2024-07-15T09:48:03.569+0000] {standard_task_runner.py:85} INFO - Job 404: Subtask run_notebook
[2024-07-15T09:48:03.645+0000] {task_command.py:410} INFO - Running <TaskInstance: run_jupyter_notebook.run_notebook scheduled__2023-12-19T00:00:00+00:00 [running]> on host bd21a2046053
[2024-07-15T09:48:03.820+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_jupyter_notebook' AIRFLOW_CTX_TASK_ID='run_notebook' AIRFLOW_CTX_EXECUTION_DATE='2023-12-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-19T00:00:00+00:00'
[2024-07-15T09:48:06.935+0000] {client.py:566} ERROR - Error occurred while starting new kernel client for kernel 099c7dd9-eafb-44b6-bb91-8e6880f92651: Kernel died before replying to kernel_info
[2024-07-15T09:48:06.937+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/run_notebook.py", line 16, in execute_notebook
    ep.preprocess(nb, {'metadata': {'path': os.path.dirname(notebook_path)}})
  File "/home/airflow/.local/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 94, in preprocess
    with self.setup_kernel():
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.7/site-packages/nbclient/client.py", line 599, in setup_kernel
    self.start_new_kernel_client()
  File "/home/airflow/.local/lib/python3.7/site-packages/jupyter_core/utils/__init__.py", line 98, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/nbclient/client.py", line 562, in async_start_new_kernel_client
    await ensure_async(self.kc.wait_for_ready(timeout=self.startup_timeout))
  File "/home/airflow/.local/lib/python3.7/site-packages/jupyter_core/utils/__init__.py", line 110, in ensure_async
    result = await obj
  File "/home/airflow/.local/lib/python3.7/site-packages/jupyter_client/client.py", line 202, in _async_wait_for_ready
    raise RuntimeError("Kernel died before replying to kernel_info")
RuntimeError: Kernel died before replying to kernel_info
[2024-07-15T09:48:06.951+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=run_jupyter_notebook, task_id=run_notebook, execution_date=20231219T000000, start_date=20240715T094803, end_date=20240715T094806
[2024-07-15T09:48:06.965+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 404 for task run_notebook (Kernel died before replying to kernel_info; 8351)
[2024-07-15T09:48:06.996+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-07-15T09:48:07.013+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
