[2024-07-15T10:38:58.122+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2023-04-14T00:00:00+00:00 [queued]>
[2024-07-15T10:38:58.136+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2023-04-14T00:00:00+00:00 [queued]>
[2024-07-15T10:38:58.140+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-15T10:38:58.163+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_notebook> on 2023-04-14 00:00:00+00:00
[2024-07-15T10:38:58.182+0000] {standard_task_runner.py:57} INFO - Started process 4456 to run task
[2024-07-15T10:38:58.188+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_remote_jupyter_notebook', 'run_notebook', 'scheduled__2023-04-14T00:00:00+00:00', '--job-id', '675', '--raw', '--subdir', 'DAGS_FOLDER/run_notebook.py', '--cfg-path', '/tmp/tmpatm31ywn']
[2024-07-15T10:38:58.191+0000] {standard_task_runner.py:85} INFO - Job 675: Subtask run_notebook
[2024-07-15T10:38:58.300+0000] {task_command.py:410} INFO - Running <TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2023-04-14T00:00:00+00:00 [running]> on host ddd5ef3b0a5c
[2024-07-15T10:38:58.758+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_remote_jupyter_notebook' AIRFLOW_CTX_TASK_ID='run_notebook' AIRFLOW_CTX_EXECUTION_DATE='2023-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-14T00:00:00+00:00'
[2024-07-15T10:38:58.777+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/run_notebook.py", line 20, in execute_remote_notebook
    notebook_content = response.json()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-15T10:38:58.788+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=run_remote_jupyter_notebook, task_id=run_notebook, execution_date=20230414T000000, start_date=20240715T103858, end_date=20240715T103858
[2024-07-15T10:38:58.800+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 675 for task run_notebook (Expecting value: line 1 column 1 (char 0); 4456)
[2024-07-15T10:38:58.823+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-07-15T10:38:58.844+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-18T06:55:01.368+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2023-04-14T00:00:00+00:00 [queued]>
[2024-07-18T06:55:01.389+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2023-04-14T00:00:00+00:00 [queued]>
[2024-07-18T06:55:01.391+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-18T06:55:01.422+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_notebook> on 2023-04-14 00:00:00+00:00
[2024-07-18T06:55:01.436+0000] {standard_task_runner.py:57} INFO - Started process 5618 to run task
[2024-07-18T06:55:01.442+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'run_remote_jupyter_notebook', 'run_notebook', 'scheduled__2023-04-14T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/run_notebook.py', '--cfg-path', '/tmp/tmpc40ao390']
[2024-07-18T06:55:01.446+0000] {standard_task_runner.py:85} INFO - Job 105: Subtask run_notebook
[2024-07-18T06:55:01.560+0000] {task_command.py:410} INFO - Running <TaskInstance: run_remote_jupyter_notebook.run_notebook scheduled__2023-04-14T00:00:00+00:00 [running]> on host 6c8b3b9a6388
[2024-07-18T06:55:01.806+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_remote_jupyter_notebook' AIRFLOW_CTX_TASK_ID='run_notebook' AIRFLOW_CTX_EXECUTION_DATE='2023-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-14T00:00:00+00:00'
[2024-07-18T06:55:08.301+0000] {logging_mixin.py:149} INFO - Notebook executed and updated successfully on the server.
[2024-07-18T06:55:08.303+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-07-18T06:55:08.322+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=run_remote_jupyter_notebook, task_id=run_notebook, execution_date=20230414T000000, start_date=20240718T065501, end_date=20240718T065508
[2024-07-18T06:55:08.383+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-07-18T06:55:08.417+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
